# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: This is my personal site
email: edvin@sladic.se
author: Edvin Sladic
description: >- # this means to ignore newlines until "baseurl:"
  Edvin Sladic - Student, developer, programmer, football player, soon to be computer science engineer & soon to be pilot.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sladic.se" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: edvinsladic
github_username:  edvinnn
linkedin_username: edvin-sladic
instagram_username: upsettingedvin

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
